<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MP3Player</RootNamespace>
    <AssemblyName>MP3Player</AssemblyName>
    <ApplicationIcon>ss.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="music-player.html" />
  </ItemGroup>

  <!-- TagLibSharp for reading MP3 metadata + cover art -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <!-- Windows Media Player COM reference for audio playback -->
  <ItemGroup>
    <COMReference Include="WMPLib">
      <Guid>{6BF52A50-394A-11D3-B153-00C04F79FAA6}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ss.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="music-player.html" />
  </ItemGroup>

</Project>
